title: Microlife

logo: profile.png # Use a relative path to logo image 

description: A card game about pathogens, mutations and crushing your opponents immune system


#theme: jekyll-theme-minimal 
