
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

ignore_theme_config: true

layout: default
title: Microlife
logo: profile.png
description: A card game about pathogens, mutations and crushing your opponents immune system